
main = "index.js"
compatibility_date = "2022-05-03"


[env]
    [env.prod]
    name = "chatme"
        [env.prod.vars]
            GROUP_ID = ""
            GROUPME_ACCESS_TOKEN = ""
            BOT_USER_ID = ""
            BOT_TOKEN = ""
            OPENAI_TOKEN = ""
            STARTER_PROMPT = "You are a helpful assistant named DinoBot."

    [env.code]
        name = "codechat"
        [env.code.vars]
            CODECHAT = true
            GROUP_ID = ""
            GROUPME_ACCESS_TOKEN = ""
            BOT_USER_ID = ""
            BOT_TOKEN = ""
            OPENAI_TOKEN = ""
            STARTER_PROMPT = "You are a helpful assistant."
    [env.dev]
        [env.dev.vars]
            GROUP_ID = ""
            GROUPME_ACCESS_TOKEN = ""
            BOT_USER_ID = ""
            BOT_TOKEN = ""
            OPENAI_TOKEN = ""
            STARTER_PROMPT = "You are a playful assistant named DinoBot."
